// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	"time"

	v1alpha3 "istio.io/client-go/pkg/apis/networking/v1alpha3"
	scheme "istio.io/client-go/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// WorkloadGroupsGetter has a method to return a WorkloadGroupInterface.
// A group's client should implement this interface.
type WorkloadGroupsGetter interface {
	WorkloadGroups(namespace string) WorkloadGroupInterface
}

// WorkloadGroupInterface has methods to work with WorkloadGroup resources.
type WorkloadGroupInterface interface {
	Create(*v1alpha3.WorkloadGroup) (*v1alpha3.WorkloadGroup, error)
	Update(*v1alpha3.WorkloadGroup) (*v1alpha3.WorkloadGroup, error)
	UpdateStatus(*v1alpha3.WorkloadGroup) (*v1alpha3.WorkloadGroup, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha3.WorkloadGroup, error)
	List(opts v1.ListOptions) (*v1alpha3.WorkloadGroupList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha3.WorkloadGroup, err error)
	WorkloadGroupExpansion
}

// workloadGroups implements WorkloadGroupInterface
type workloadGroups struct {
	client rest.Interface
	ns     string
}

// newWorkloadGroups returns a WorkloadGroups
func newWorkloadGroups(c *NetworkingV1alpha3Client, namespace string) *workloadGroups {
	return &workloadGroups{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the workloadGroup, and returns the corresponding workloadGroup object, and an error if there is any.
func (c *workloadGroups) Get(name string, options v1.GetOptions) (result *v1alpha3.WorkloadGroup, err error) {
	result = &v1alpha3.WorkloadGroup{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("workloadgroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of WorkloadGroups that match those selectors.
func (c *workloadGroups) List(opts v1.ListOptions) (result *v1alpha3.WorkloadGroupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha3.WorkloadGroupList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("workloadgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested workloadGroups.
func (c *workloadGroups) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("workloadgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a workloadGroup and creates it.  Returns the server's representation of the workloadGroup, and an error, if there is any.
func (c *workloadGroups) Create(workloadGroup *v1alpha3.WorkloadGroup) (result *v1alpha3.WorkloadGroup, err error) {
	result = &v1alpha3.WorkloadGroup{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("workloadgroups").
		Body(workloadGroup).
		Do().
		Into(result)
	return
}

// Update takes the representation of a workloadGroup and updates it. Returns the server's representation of the workloadGroup, and an error, if there is any.
func (c *workloadGroups) Update(workloadGroup *v1alpha3.WorkloadGroup) (result *v1alpha3.WorkloadGroup, err error) {
	result = &v1alpha3.WorkloadGroup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("workloadgroups").
		Name(workloadGroup.Name).
		Body(workloadGroup).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *workloadGroups) UpdateStatus(workloadGroup *v1alpha3.WorkloadGroup) (result *v1alpha3.WorkloadGroup, err error) {
	result = &v1alpha3.WorkloadGroup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("workloadgroups").
		Name(workloadGroup.Name).
		SubResource("status").
		Body(workloadGroup).
		Do().
		Into(result)
	return
}

// Delete takes name of the workloadGroup and deletes it. Returns an error if one occurs.
func (c *workloadGroups) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("workloadgroups").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *workloadGroups) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("workloadgroups").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched workloadGroup.
func (c *workloadGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha3.WorkloadGroup, err error) {
	result = &v1alpha3.WorkloadGroup{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("workloadgroups").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
